apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-db-password-secret
  namespace: employee
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-db-password

  data:
    - remoteRef:
        key: rdspassword
        property: rdspassword
      secretKey: password