apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-db-password-secret
  namespace: employee
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: azure-secret-store
    kind: ClusterSecretStore

  target:
    name: mysql-db-password
    creationPolicy: Owner

  data:
  - secretKey: password
    remoteRef:
      key: secret/dbpassword