apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-db-password-secret
  namespace: employee
spec:
  refreshInterval: 10s
  secretStoreRef:
    name: gcp-secret-store
    kind: ClusterSecretStore
  target:
    name: mysql-db-password
    creationPolicy: Owner

  data:
    - remoteRef:
         key: password
      secretKey: password