apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
        tier: frontend
    spec:
      containers:
        - name: employee-frontend
          image: us-east1-docker.pkg.dev/single-portal-443110-r7/nginxapp/employee-frontend:v0.0.44-58
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
          resources:
            requests:
              memory: "100Mi"
              cpu: "120m"
            limits:
              memory: "150Mi"
              cpu: "200m"
          readinessProbe:
            httpGet:
              scheme: HTTP
              path: /
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 15
            timeoutSeconds: 5
        