apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gmail-secret
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: gmail-auth

  data:
    - remoteRef:
        key: email
        property: email
      secretKey: password