apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-secret-store
  namespace: monitoring
spec:
  provider:
    vault:
      server: "https://kmsvault.cncloudnet.com:8200"
      path: "secret"
      version: "v2"
      auth:
        tokenSecretRef:
          name: "vault-token"
          namespace: "monitoring"
          key: "token"