apiVersion: v1
kind: Service
metadata:
  name: employee-frontend-service
  labels:
    app: employee-frontend
    tier: frontend
spec:
  type: ClusterIP
  selector:
    app: employee-frontend
  ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http