apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: employee-backend-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: employee-backend
  minReplicas: 2
  maxReplicas: 10
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50 
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 70 
