apiVersion: v1
stringData:
  VAULT_ADDR: https://kmsvault.cncloudnet.com:8200
  VAULT_TOKEN: hvs.iMeZFjEFohtGS753ZWXYA9EN
  AVP_TYPE: vault
  AVP_AUTH_TYPE: token
kind: Secret
metadata:
  name: vault-configuration
  namespace: argocd
type: Opaque