apiVersion: v1
kind: Service
metadata:
  name: employee-backend-service
  labels:
    app: employee-backend
    tier: backend
  annotations:
    alb.ingress.kubernetes.io/healthcheck-path: /actuator/health
spec:
  type: ClusterIP
  selector:
    app: employee-backend
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
