apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
  labels:
    tier: backend
    app: employee-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        tier: backend
        app: employee-backend
    spec:
      initContainers:
        - name: mydb-available
          image: busybox:1.28
          command: ['sh','-c',"until nslookup 34.31.45.25; do echo waiting for database; sleep 4; done"]
      containers:
        - name: employee-backend
          image: fadhiljr/nginxapp:employee-backend-v0.0.29-40
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "employee"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://34.31.45.25:3306/employeemanager"
            - name: SPRING_DATASOURCE_USERNAME
              value: "root"
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: mysql-db-password
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"
         # readinessProbe:
          #  httpGet:
           #   scheme: HTTP
            #  path: /actuator/health
             # port: 8080
            #initialDelaySeconds: 10
            #periodSeconds: 15
            #timeoutSeconds: 5
            
              