apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: my-backendconfig-cdn
  namespace: employee
spec:
  timeoutSec: 42 
  connectionDraining: 
    drainingTimeoutSec: 62
  logging: 
    enable: true
    sampleRate: 1.0
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: false  