apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-backend
  labels:
    tier: backend
    app: employee-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-backend
  template:
    metadata:
      labels:
        tier: backend
        app: employee-backend
    spec:
      containers:
        - name: employee-backend
          image: fadhiljr/nginxapp:employee-backend-v0.0.11-183
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_APPLICATION_NAME
              value: "employee"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:mysql://employeemanager.c9iouucc2x0o.us-east-1.rds.amazonaws.com:3306/employeemanager"
            - name: SPRING_DATASOURCE_USERNAME
              value: "admin"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "AhwRrvWIdTupcSKRHRZO"
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          livenessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 8080
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            requests:
              cpu: "200m"
              memory: "128Mi"
            limits:
              cpu: "250m"
              memory: "250Mi"