apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
        tier: frontend
    spec:
      containers:
        - name: employee-frontend
          image: replace
          ports:
            - containerPort: 80
          securityContext:
            runAsNonRoot: true
            runAsUser: 100
          resources:
            requests:
              memory: "250Mi"
              cpu: "650m"
            limits:
              memory: "400Mi"
              cpu: "750m"
