apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: employee-mgmt-ingress
  annotations:
    kubernetes.io/ingress.global-static-ip-name: "gke-ingress-external"   
    networking.gke.io/managed-certificates: managed-cert-ingress
    networking.gke.io/v1beta1.FrontendConfig: "frontend-config"
spec:
  ingressClassName: gce
  rules:
  - host: gcpdev.cloud-emgmt.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: employee-frontend-service
            port: 
              number: 80
  - host: gcp.cloud-emgmt.com
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: employee-backend-service
            port: 
              number: 80

