apiVersion: v1
kind: Namespace
metadata:
  name: employee
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: employee
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: employee
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: employee
rules:
  - apiGroups: [""] 
    resources: ["pods", "services", "replicationcontrollers"]
    verbs: ["get", "list", "create", "delete"]
  - apiGroups: ["apps"]
    resources: ["deployments", "daemonsets", "statefulsets"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["autoscaling"]
    resources: ["horizontalpodautoscalers"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: ["batch"]
    resources: ["cronjobs", "jobs"]
    verbs: ["get", "list", "create", "delete", "patch", "update"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["impersonate"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: employee
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: employee
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
