apiVersion: v1
kind: Namespace
metadata:
  name: employee
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: employee
---
apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: employee
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: employee
rules:
  - apiGroups:
      - ""
      - apps
      - autoscaling
      - batch
      - extensions
      - policy
      - rbac.authorization.k8s.io
    resources:
      - pods
      - services
      - replicationcontrollers
      - secrets
      - deployments
      - daemonsets
      - statefulsets
      - horizontalpodautoscalers
      - cronjobs
      - jobs
      - serviceaccounts
      - configmaps
      - events
      - endpoints
      - ingress
      - namespaces
      - clusterrolebindings
      - clusterroles
      - replicasets
      - persistentvolumes
      - persistentvolumeclaims
      - limitranges
      - resourcequotas
    verbs: ["get", "list", "create", "delete", "update", "patch", "watch","impersonate"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: employee
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: employee
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
