server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://employeemanager-sts.cl402myc20q2.us-east-1.rds.amazonaws.com:3306/employeemanager
    username: admin
    password: NpRdw03EywDQxrtQ6zG7
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"