server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://34.60.38.43:3306/employeemanager
    username: root
    password: fadhil1234
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"