server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://employeemanager.mysql.database.azure.com:3306/employeemanager
    username: employee
    password: fadhil1234#
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"