server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://employeemanager.c9iouucc2x0o.us-east-1.rds.amazonaws.com:3306/employeemanager
    username: admin
    password: iPXLp5oDj63buCkWvHlT
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"