server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://employeemanager.cfmyc6cwork3.us-east-1.rds.amazonaws.com:3306/employeemanager
    username: admin
    password: Fadhil1234##*
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"
    
management:
  endpoints:
    web:
      exposure:
        include: "*"