server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://54.87.49.59:3306/employeemanager
    username: admin
    password: admin123
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  sql:
    init:
      mode: always
  application:
    name: "employee"