apiVersion: v1
kind: Namespace
metadata:
  name: employee
---

apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins
  namespace: employee
---

apiVersion: v1
kind: Secret
metadata:
  name: jenkins-token
  namespace: employee
  annotations:
    kubernetes.io/service-account.name: jenkins
type: kubernetes.io/service-account-token

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jenkins-role
  namespace: employee
rules:
- apiGroups:
  - ""
  resources:
  - services
  - pods
  - secrets
  - configmaps
  - persistentvolumes
  - serviceaccounts
  - replicationcontrollers
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - impersonate
  - patch
- apiGroups:
  - apps
  resources:
  - daemonsets
  - statefulsets
  - deployments
  - replicasets
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - patch
- apiGroups:
  - autoscaling
  resources:
  - horizontalpodautoscalers
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - patch
- apiGroups:
  - batch
  resources:
  - cronjobs
  - jobs
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - patch
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - patch
- apiGroups:
  - external-secrets.io
  resources:
  - externalsecrets
  verbs:
  - list
  - watch
  - describe
  - get
  - create
  - patch

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-rolebinding
  namespace: employee
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: employee
roleRef:
  kind: Role
  name: jenkins-role
  apiGroup: rbac.authorization.k8s.io
