apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}
  labels:
    app: {{ .Values.appName }}
    tier: {{ .Values.appTier }}
spec:
  replicas: 2
  selector:
    matchLabels:
      app: {{ .Values.appName }}
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        tier: {{ .Values.appTier }}
    spec:
      containers:
        - name: {{ .Values.appName }}
          image: "{{ .Values.appImage }}:{{ .Values.appVersion }}"
          ports:
            - containerPort: {{ .Values.containerPort }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
          resources:
            requests:
              memory: "100Mi"
              cpu: "120m"
            limits:
              memory: "150Mi"
              cpu: "200m"