apiVersion: v2
name: eks-argocd-vault
description: A Helm chart for Kubernetes
type: application
<<<<<<< HEAD
version: 0.1.6
=======
version: 0.1.2
>>>>>>> 476e910 (chart release added)
appVersion: "1.16.0"