apiVersion: apps/v1
kind: Deployment
metadata:
  name: employee-frontend
  labels:
    app: employee-frontend
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: employee-frontend
  template:
    metadata:
      labels:
        app: employee-frontend
        tier: frontend
    spec:
      imagePullSecrets:
        - name: aws-registry-key
      containers:
        - name: employee-frontend
          image: 522814728991.dkr.ecr.us-east-1.amazonaws.com/aws-fullstack:frontend-v0.0.24-23
          imagePullPolicy: Always
          ports:
            - containerPort: 8000
          securityContext:
            runAsNonRoot: true
            runAsUser: 101
          resources:
            requests:
              memory: "100Mi"
              cpu: "120m"
            limits:
              memory: "150Mi"
              cpu: "200m"